/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UDPClient;

import UDPClient.Client;
import UDPClient.ClientDirectoryForm;
import UDPClient.LoginForm;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author afrin
 */
public class HomeDirectoryForm extends javax.swing.JFrame {

    public String username,password,command;
    public HomeDirectoryForm() {
        initComponents();
        jPanel1.setBackground(Color.white);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2 , dim.height / 2 - this.getSize().height / 2);
    }
    public void goToLoginForm(JLabel labelName){
        LoginForm loginForm = new LoginForm();
        loginForm.TFusername.setText(labelName.getText());
        loginForm.setVisible(true);
       
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelUserPurba = new javax.swing.JLabel();
        LabelUserAfrin = new javax.swing.JLabel();
        LabelUserSadia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PordBox");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/box.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("PordBox");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelUserPurba.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        LabelUserPurba.setForeground(new java.awt.Color(170, 0, 255));
        LabelUserPurba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUserPurba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder-medium.png"))); // NOI18N
        LabelUserPurba.setText("User1");
        LabelUserPurba.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelUserPurba.setVerifyInputWhenFocusTarget(false);
        LabelUserPurba.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LabelUserPurba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelUserPurbaMouseClicked(evt);
            }
        });

        LabelUserAfrin.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        LabelUserAfrin.setForeground(new java.awt.Color(170, 0, 255));
        LabelUserAfrin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUserAfrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder-medium.png"))); // NOI18N
        LabelUserAfrin.setText("User2");
        LabelUserAfrin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelUserAfrin.setVerifyInputWhenFocusTarget(false);
        LabelUserAfrin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LabelUserAfrin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelUserAfrinMouseClicked(evt);
            }
        });

        LabelUserSadia.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        LabelUserSadia.setForeground(new java.awt.Color(170, 0, 255));
        LabelUserSadia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUserSadia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder-medium.png"))); // NOI18N
        LabelUserSadia.setText("User3");
        LabelUserSadia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelUserSadia.setVerifyInputWhenFocusTarget(false);
        LabelUserSadia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LabelUserSadia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelUserSadiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(LabelUserPurba)
                .addGap(84, 84, 84)
                .addComponent(LabelUserAfrin)
                .addGap(67, 67, 67)
                .addComponent(LabelUserSadia)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelUserPurba, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(LabelUserAfrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelUserSadia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelUserPurbaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelUserPurbaMouseClicked
        // TODO add your handling code here:
        goToLoginForm(LabelUserPurba);
        
        
        
    }//GEN-LAST:event_LabelUserPurbaMouseClicked

    private void LabelUserAfrinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelUserAfrinMouseClicked
        // TODO add your handling code here:
        goToLoginForm(LabelUserAfrin);
    }//GEN-LAST:event_LabelUserAfrinMouseClicked

    private void LabelUserSadiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelUserSadiaMouseClicked
        // TODO add your handling code here:
        goToLoginForm(LabelUserSadia);
    }//GEN-LAST:event_LabelUserSadiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeDirectoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeDirectoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeDirectoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeDirectoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeDirectoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelUserAfrin;
    private javax.swing.JLabel LabelUserPurba;
    private javax.swing.JLabel LabelUserSadia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
